name: Lint + Prettier check
on: [push, pull_request]
jobs:
  build:
    name: Run ESLint + Prettier check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Prettier
        run: yarn fmt:check

      - name: ESlint
        run: yarn lint
